DROP TABLE IF EXISTS devices;
CREATE TABLE devices (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    pin INTEGER NOT NULL UNIQUE,
    input BOOLEAN NOT NULL,
    device_type INTEGER NOT NULL,
    pull_up BOOLEAN
);